Eventbrite/config/routes.rb
Rails.application.routes.draw do
  get 'attendance/new'
  get 'attendance/create'
  # get 'attendances/new'
  # get 'attendances/create'
  # devise_for :users, module: "users"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :event

  # resources :event do
  #   get 'subscribe', on: :collection
  # end
   resources :event do
    resources :attendance, only: [:new, :create, :index]
  end
  # resources :attendances, only: [:new, :create]
  post '/event/subscribe/:id', to: 'event#subscribe', as: 'subscribe_event'
  resources :users,  only: [:show, :edit, :update]  

  root :to => "event#index"
  
  
  
  
  
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'user/show'
  # get 'user/edit'
  # get 'user/update'
  # get 'event/index'
  # get 'event/new'
  # get 'event/create'
  # get 'event/show'
  # get 'event/destroy'
  # get 'event/edit'
  # get 'event/update'
  # get 'static_pages/index'
  # get 'static_pages/secret'
end

Eventbrite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Eventbrite/app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

Eventbrite/app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances 

    validates :start_date,
    presence: true
    # numericality: {greater_than_or_equal_to: Time.now}

    # puts duration
    validates :duration,
    presence: true
    # numericality: {equal_to: :duration % 5 }
    
    validates :title,
    presence: true,
    length: {in: 5..140}

    validates :description,
    presence: true,
    length: {in: 20..1000}

    validates :price,
    presence: true,
    numericality: { only_integer: true }

    validates :location,
    presence: true
end

Eventbrite/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send
  
    has_many :attendances
    has_many :event, through: :attendances 

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

Eventbrite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Eventbrite/app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  before_action :authenticate_user, only: [:index]
  def index
    @event = Event.all.find(params[:event_id])
    @attendances = Attendance.where(event_id: [@event.id]) 
    @users =  User.where(id: [@attendances.ids])    
  end

  def new
    @event = Event.all.find(params[:event_id])
    @attendances = Attendance.new
    @user = current_user
  end

  def create
    puts "-"*60
    puts "start"
    puts "-"*60
    
    @event = Event.all.find(params[:id])
    if @event.user_id.include? current_user.id
      flash[:error] = "Vous participez deja a l'evenement."
      redirect_to show_path and return
    end
    @amount = @event.price
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Paiement du client',
      currency: 'eur',
    })
  
    @event.user_id << current_user
    @attendances.strip_customer_id
    flash[:success] = "Vous etes inscrit a l'evenement"
    redirect_to event_path and return
  
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    puts "/"*60
    puts "end"
    puts "/"*60
  end




    
      private

  def authenticate_user
    @event = Event.all.find(params[:event_id])
    if current_user.id != @event.user_id
      flash[:danger] = "Please log in."
      redirect_back(fallback_location: event_path(@event.id))
      # redirect_to event_path.(@event.id) and return
    end
  end


end

Eventbrite/app/controllers/event_controller.rb
class EventController < ApplicationController
 
  def index
    @events = Event.all
    # <p class="card-text"><%= @users_event.first_name %></p>
  end

  def new
    @event = Event.new
    @user_id = current_user.id
  end

  def create
    event_params = params.require(:event).permit(:title, :description, :start_date, :duration, :location, :price , :user_id)
    @event = Event.new(event_params)
    puts @event
    if (@event.save)

      redirect_to event_path(@event.id), :flash => {:success => "Vous avez bien cree l'event"} and return
    else
      flash[:error] = "Create event not working. #{@event.errors.full_messages}"
      render new_event_path and return
    end
  end

  
  def show
    @event = Event.all.find(params[:id])
    @attendances = Attendance.all
    puts @attendances
    puts "*"*60
    puts @attendances
  end

  # <% if @attendances.user_id.count %>
  #   <p>Nombre de participant : <%= @attendances.user_id.count%></p>
  #   <% end%>
  
  def destroy
    @event = Event.all.find(params[:id])
    @event.delete
    redirect_to root_path, :flash => {:success => "Vous avez bien delete le gossip"} and return
  end
  
  def edit
    @event = Event.all.find(params[:id])
  end

  def update
    @event = Event.all.find(params[:id])
    event_params = params.require(:event).permit(:title, :description, :start_date, :duration, :location, :price )
    @event.update(event_params, user_id: current_user.id)
  end

  # def subscribe
  #   puts "-"*60
  #   puts "start"
  #   puts "-"*60
  #   @event = Event.all.find(params[:id])
  #   # if @event.user_id.include? current_user
  #   #   flash[:error] = "Vous participez deja a l'evenement."
  #   #   redirect_to "#", show_path and return
  #   # end
    
  #   @amount = @event.price
  #   customer = Stripe::Customer.create({
  #     email: params[:stripeEmail],
  #     source: params[:stripeToken],
  #   })
  
  #   charge = Stripe::Charge.create({
  #     customer: customer.id,
  #     amount: @amount,
  #     description: 'Paiement du client',
  #     currency: 'eur',
  #   })
  
  #   # @event.user_id << current_user
  #   # flash[:success] = "Vous etes inscrit a l'evenement"
  #   # redirect_to event_path and return
  
  # # rescue Stripe::CardError => e
  # #   flash[:error] = e.message
  # #   redirect_to new_charge_path
  # # end
  # puts "/"*60
  #   puts "end"
  #   puts "/"*60
  # end

 
end



# <%= form_tag subscribe_event_path(@event.id) do %>
#   <article>
#       <% if flash[:error].present? %>
#       <div id="error_explanation">
#           <p><%= flash[:error] %></p>
#       </div>
#       <% end %>
#       <label class="amount">
#       <p>Veuillez payez le montant de: <%= @event.price.to_f / 100  %>euro de pour l'inscription</p>
#       </label>
#   </article>

#   <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
#           data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
#           data-description="A month's subscription"
#           data-amount=<%= @event.price %>
#           data-currency= "eur"
#           data-locale="auto">
#   </script>
# <% end %>

Eventbrite/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

Eventbrite/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    
  end

  def update
    @user = User.all.find(params[:id])
    user_params = params.require(:user).permit(:first_name, :last_name, :description)
    @user.update(user_params)
    redirect_to user_path, :flash => {:success => "Vous bien update le gossip"} and return
   end


  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

Eventbrite/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
      :user
  end

  def resource
      @resource ||= User.new
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
      devise_mapping.to
  end
end

Eventbrite/app/helpers/attendance_helper.rb
module AttendanceHelper
end

Eventbrite/app/helpers/event_helper.rb
module EventHelper
end

Eventbrite/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Eventbrite/app/helpers/user_helper.rb
module UserHelper
end

Eventbrite/app/helpers/users_helper.rb
module UsersHelper
end

Eventbrite/app/views/attendance/create.html.erb
<h1>Attendance#create</h1>
<p>Find me in app/views/attendance/create.html.erb</p>

Eventbrite/app/views/attendance/index.html.erb
<div class="container">
   <div class="text-center border border-secondary rounded">
        <%= link_to "Modifier l'event", edit_event_path(@event.id), class: "btn btn-primary"%>
        <%= link_to "Delete l'event", "#", class: "btn btn-danger"%>
        <h4>Les invitez sont : </h4>
        <%@users.each do |user|%>
            <p><%= user.first_name %> <%= user.last_name %></p>
        <% end %>
    </div>
</div>

Eventbrite/app/views/attendance/new.html.erb
<h1>Attendance#new</h1>
<p>Find me in app/views/attendance/new.html.erb</p>

<div class="container">
    <div class="text-center">
        <% if current_user %>
            <%= form_tag url: {action: "create"} do %>
                <article>
                    <% if flash[:error].present? %>
                    <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                    </div>
                    <% end %>
                    <label class="amount">
                    <p>Veuillez payez le montant de: <%= @event.price.to_f / 100  %>euro pour l'inscription</p>
                    </label>
                </article>

                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="Te voila inscrit"
                        data-amount=<%= @event.price %>
                        data-currency= "eur"
                        data-locale="auto">
                </script>
            <% end %>
        <% else %>
                <%= render :file =>"devise/registrations/new"%>
        <% end %>
  </div><!-- text-center-->
</div><!-- container -->

Eventbrite/app/views/event/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

Eventbrite/app/views/event/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

Eventbrite/app/views/event/edit.html.erb
<h1>Event#edit</h1>
<p>Find me in app/views/event/edit.html.erb</p>
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 border border-info ">
      <br><br><br>

      <% if @event.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>Nous n'avons pas réussi à créer l'event pour la(les) raison(s) suivante(s) :</p>
          <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for :event, url: {action: "create"} do |f| %>
      <h1 class="h3 mb-3 font-weight-normal text-center">Creer un Event </h1>
        <div class="form_group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label "format yyyy/mm/dd" %><!-- trouver un moyen pour separer heure et jours-->
          <%= f.text_field :start_date, class: "form-control"%>
        </div>
        <br>
         <div class="form_group">
          <%= f.label :duration %>
          <%= f.text_field :duration, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label :price  %>
          <%= f.text_field :price, class: "form-control"%>
        </div>
        <br>
        <div class="actions mt-5">
          <%= f.submit "Valider", class: "btn btn-lg btn-primary btn-block" %>
        </div>
        <br>
      <% end %>
   </div>
  </div>
</div>

Eventbrite/app/views/event/index.html.erb
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Hello, world! Eventbrite.</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
      </div>
        <div class="album py-5 bg-light">
            <div class="container">
            
                <div class="card-columns">
                    <%@events.each do |event|%>
                        <div class="card border-info">
                            <%= link_to  event_path(event.id) do %>
                            <%= image_tag "https://thumbs.dreamstime.com/z/red-fox-sunrise-female-poses-gracefully-morning-sun-162386398.jpg", class: "card-img-top" %>
                            <% end %>
                            <div class="card-body">
                                <h5 class="card-title"><%= event.title %></h5>
                                <p class="card-text"><%= event.description %></p>
                                <p class="card-text"><%= event.start_date %></p>
                                
                                <p class="card-text text-center">
                                <!-- ajuster le last update pour avoir les minutes-->
                                    <small class="text-muted">Last updated <%= event.updated_at %> mins ago</small>
                                </p>
                                <div class="card-footer">
                                    <small class="text-muted">Last updated <%= event.updated_at %>mins ago </small>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>

                    <!-- /row -->
                <hr>
            </div> <!-- /container -->
        </div><!-- /album py-5 bg-light -->
    </main>

Eventbrite/app/views/event/new.html.erb
<h1>Event#new</h1>
<p>Find me in app/views/event/new.html.erb</p>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 border border-info ">
      <br><br><br>

      <% if @event.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>Nous n'avons pas réussi à créer l'event pour la(les) raison(s) suivante(s) :</p>
          <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for :event, url: {action: "create"} do |f| %>
      <h1 class="h3 mb-3 font-weight-normal text-center">Creer un Event </h1>
       <%= f.hidden_field :user_id, value: @user_id, class: "form-control"%>
        <div class="form_group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label "format yyyy/mm/dd" %><!-- trouver un moyen pour separer heure et jours-->
          <%= f.text_field :start_date, class: "form-control"%>
        </div>
        <br>
         <div class="form_group">
          <%= f.label :duration %>
          <%= f.text_field :duration, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control"%>
        </div>
        <br>
        <div class="form_group">
          <%= f.label :price  %>
          <%= f.text_field :price, class: "form-control"%>
        </div>
        <br>
        <div class="actions mt-5">
          <%= f.submit "Valider", class: "btn btn-lg btn-primary btn-block" %>
        </div>
        <br>
      <% end %>
   </div>
  </div>
</div>

Eventbrite/app/views/event/show.html.erb
<div class="container">
    <div class="text-center">
        <h1>Event#show</h1>
        <p>Find me in app/views/event/show.html.erb</p>      
        <% if current_user && current_user.id == @event.user_id%>
            <%= link_to "mon espace événement", event_attendance_index_path(@event.id) , class: "btn btn-warning"%>
        <% end %>
        <div class="text-center border border-secondary rounded">
        <h3><%= @event.title%></h3>
        <p>Description : <%= @event.description%></p>
        <!-- nombre d'user inscrit a l evenement-->
        <p>Date de commencement : <%= @event.start_date%></p> <!-- Afficher au bon format jours mois annee avec l'horaire-->
        <p>Duree : <%= @event.duration%></p>
        <p>Lieu : <%= @event.location%></p>
        <p>Prix :  <%= @event.price%></p>    
    <% if current_user %>
        <%= link_to "Rejoindre l'event",  new_event_attendance_path(@event.id), class: "btn btn-success"%>
    <% else %>
        <%= link_to "inscription", new_user_registration_path, :class => "btn btn-primary" %> 
<% end %>
    </div><!-- text-center-->
</div><!-- container -->
<%# <div class="text-center"> %>

<%# </div> %>

Eventbrite/app/views/event/update.html.erb
<h1>Event#update</h1>
<p>Find me in app/views/event/update.html.erb</p>

Eventbrite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to "Home", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse  d-flex justify-content-between" id="navbarTogglerDemo02">
    <ul class="navbar-nav ">
      <li class="nav-item active">
      
       <% if current_user %>
        <%= link_to "Creer un evenement", new_event_path, class: "nav-link" %>
      <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "inscription", new_user_registration_path, :class => "nav-link" %>
      </li>
    </ul>
    <% if current_user %>
    <div class="nav-item dropdown">
      <%= link_to "Profil/Sign out", "", :class => "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { toggle: "dropdown"}, aria: {haspopup: "true"}, aria: { expanded: "false"}%>
      <div class="dropdown-menu dropdown-menu-right"  aria-labelledby="navbarDropdown">
          <%= link_to "profil",  user_path(current_user), :class => "dropdown-item"%>
          <div class="dropdown-divider"></div>
          <%= link_to "sign out", destroy_user_session_path, :class => "dropdown-item", :method => :delete%>
      </div>
    </div>
    <% else %>
      <div class="nav-item dropdown">
        <%= link_to "Inscription/Sign in", "", :class => "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { toggle: "dropdown"}, aria: {haspopup: "true"}, aria: { expanded: "false"}%>
        <div class="dropdown-menu dropdown-menu-right"  aria-labelledby="navbarDropdown">
          <%= link_to "inscription", new_user_registration_path, :class => "dropdown-item" %>        
          <div class="dropdown-divider"></div>
          <%= link_to "Sign in", new_user_session_path, :class => "dropdown-item" %>
      </div>
    </div>
    <% end %>

  </div>
</nav>
<% if flash[:success]%>
<div class="alert alert-success" role="alert">
  <%= flash[:success]%>
</div>
<% end %>
<%= yield %>
  </body>
</html>

Eventbrite/app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

Eventbrite/app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

Eventbrite/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @user, url: {action: "update"} do |f| %>
      <h1 class="h3 mb-3 font-weight-normal text-center">Edit profile</h1>
        <div class="form_group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: "form-control"%>
        </div>
        <div class="form_group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: "form-control"%>
        </div>
        <div class="form_group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control"%>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Edit", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
   </div>
  </div>
</div>

Eventbrite/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= link_to "edit profil", edit_user_path(@user.id), :class => "nav-link" %>
<%= link_to "edit compte", edit_user_registration_path, :class => "nav-link" %>
<p><%= @user.first_name%></p>
<p><%= @user.last_name%></p>
<p> <%= @user.description%></p>
<p> <%= @user.email%></p>
<p> <%= @user.event_id%></p>

Eventbrite/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>